baseURL = "/"
title = "Fireact Documentation"
theme = ["docsy"]
enableGitInfo = true

# Language settings
contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

# Image processing configuration
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango"

# Site Parameters
[params]
copyright = "The Fireact Authors"
privacy_policy = "https://policies.google.com/privacy"

# Repository configuration
github_repo = "https://github.com/fireact-dev/main"
github_branch = "main"

# Enable Lunr.js offline search
offlineSearch = true

# User interface configuration
[params.ui]
sidebar_menu_compact = true
breadcrumb_disable = false
sidebar_search_disable = false
navbar_logo = true
footer_about_enable = true

# Feedback configuration
[params.ui.feedback]
enable = true
yes = 'Glad to hear it! Please <a href="https://github.com/fireact-dev/main/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/fireact-dev/main/issues/new">tell us how we can improve</a>.'

# Language configuration
[languages]
[languages.en]
title = "Fireact Documentation"
languageName ="English"
weight = 1

[languages.en.params]
description = "Documentation for Fireact"

# Module configuration
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"

# Top Navigation Menu
[[menu.main]]
name = "Demos"
url = "https://fireact.dev/demos/"
weight = 20
identifier = "demos"

[[menu.main]]
name = "Blog"
url = "https://fireact.dev/blog/"
weight = 40
identifier = "blog"

[[menu.main]]
name = "Roadmap"
url = "https://github.com/orgs/fireact-dev/projects/1"
weight = 50
identifier = "roadmap"

[[menu.main]]
name = "Github"
url = "https://github.com/fireact-dev/main"
weight = 60
identifier = "github"
